openapi: 3.0.1
info:
  title: Analytics Service API
  version: 1.0.0
paths:
  /analytics/metrics:
    get:
      summary: Retrieve analytics metrics
      responses:
        "200":
          description: Metrics data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Metric"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
components:
  schemas:
    Metric:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        value:
          type: number
        timestamp:
          type: string
          format: date-time
