openapi: 3.1.0
info:
  title: Order Service API
  version: 1.0.0
paths:
  /orders:
    post:
      summary: Create a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderRequest"
      responses:
        "201":
          description: Order created successfully
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /orders/{id}:
    get:
      summary: Retrieve order by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Order retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderResponse"
        "404":
          description: Order not found
        "500":
          description: Internal Server Error
components:
  schemas:
    OrderRequest:
      type: object
      properties:
        items:
          type: array
          items:
            type: string
        total:
          type: number
    OrderResponse:
      type: object
      properties:
        id:
          type: string
        items:
          type: array
          items:
            type: string
        total:
          type: number
        status:
          type: string
