openapi: 3.1.0
info:
  title: File Service API
  version: 1.0.0
paths:
  /files:
    post:
      summary: Upload a file
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "201":
          description: File uploaded successfully
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
  /files/{fileId}:
    get:
      summary: Download a file
      parameters:
        - in: path
          name: fileId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: File download
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: File not found
        "500":
          description: Internal Server Error
components: {}
