openapi: 3.1.0
info:
  title: Admin Service API
  version: 1.0.0
paths:
  /admin/users:
    get:
      summary: Get all admin users
      responses:
        "200":
          description: List of admin users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AdminUser"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
    post:
      summary: Create a new admin user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AdminUser"
      responses:
        "201":
          description: Admin user created
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
components:
  schemas:
    AdminUser:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        role:
          type: string
